### ISSUE TITLE
Add support to use mountpoint-s3 as a docker volume driver using a plugin

### ISSUE THREAD

**Issue by aek** [awslabs/mountpoint-s3#993]
### Tell us more about this new feature.

For those who are interested in using this project in docker projects I have created a Docker Volume Plugin in order facilitate the usage of mountpoint-s3 in Docker Compose via a driver and driver_opts.

You could find the plugin public and ready to be installed from DockerHub
https://hub.docker.com/r/aekis/docker-mount-s3

The project is also hosted on Github
https://github.com/aekis-dev/docker-mount-s3

Example usage:
```
name: fe4d6eca
services:
  service_name:
    image: image_name
    volumes:
    - type: volume
      source: volume_name
      target: /s3/bucket/data
  volumes:
    volume_name:
      driver: aekis/docker-mount-s3
      driver_opts:
        bucket: bucket_name
        AWS_ACCESS_KEY_ID: XXXXXXAWS_ACCESS_KEY_IDXXXXXXX
        AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXAWS_SECRET_ACCESS_KEYXXXXXXXXXXXX
        o: --allow-delete --allow-overwrite --allow-other --region=us-east-1
```
